### ISSUE TITLE
Piface Digital 2 InterruptEnableException

### ISSUE THREAD

**Issue by simonsmart99** [piface/pifacedigitalio#24] opened 2015-02-10 14:58 UTC
Hi all

I am VERY new to Raspberry pi and linux in general, so please excuse the noob questions.

I have followed the Piface Digital 2 installation instructions to the letter, however receive an interrupt error on line 213 of the Interrupts.py script when I try to run the blink.py script. I am using python 2 by default, but have tried to run the blink.py script under both python 2 and 3. I have attached response in both versions. 

At first I thought the problem may relate to the SPI driver, but I have enabled the port and tested it by bridging the MOSI and MISO pins and running spidev_test.c. I receive the correct response.

python 2 

![start using python2](https://cloud.githubusercontent.com/assets/10942706/6129278/08642984-b135-11e4-9e18-c076efe47274.jpg)

python 3

![start using python3](https://cloud.githubusercontent.com/assets/10942706/6129290/23ca3114-b135-11e4-9410-dbe2af543c97.jpg)

Any help would be greatly appreciated.
Kind regards
Simon

**Comment by tompreston** [comment] 2015-04-16 08:51
Hi, there appears to be a bug with our interrupt exception handler in your example, however the root cause is actually to do with the software not finding the GPIO pins. If I remember correctly this was because they moved after a kernel update (or something like that). Anyway, all should be fixed now. Can you try updating with:

    sudo apt-get update
    sudo apt-get upgrade

to see if that fixes your issue?

**Closed** 2015-07-21 10:34 UTC
